"""Opens each built version in Chromium and drives every feature. Prints PASS/FAIL lines."""
import sys, pathlib
from playwright.sync_api import sync_playwright
SHOTS = pathlib.Path('/tmp/claude-0/-home-claude/1a34ac8d-b6d4-5a9c-8b16-78338b6c1bbd/scratchpad')
res = []
def check(name, ok, detail=''):
    res.append(ok); print(('PASS ' if ok else 'FAIL ') + name + (('  ' + str(detail)) if detail and not ok else ''))

with sync_playwright() as p:
    b = p.chromium.launch()
    for ver in ('10.4',):
        ctx = b.new_context(viewport={'width': 1280, 'height': 900})
        ctx.route('http*://**/*', lambda r: r.abort())   # sandbox has no internet; images fall back
        pg = ctx.new_page(); errs = []
        pg.on('pageerror', lambda e: errs.append(str(e)))
        pg.goto(f'file:///home/claude/work/site_v{ver}/index.html?date=2026-10-08T12:00:00-04:00'); pg.wait_for_timeout(400)
        check(f'v{ver} loads without script errors', not errs, errs)
        check(f'v{ver} roster shows 100 cards', pg.locator('#grid .card').count() == 100)
        # v10 checks
        pg.select_option('#pA', 'emberpup'); pg.wait_for_timeout(150)
        txt = pg.text_content('#pChart')
        check('v10 chart shows Emberpup numbers', all(x in txt for x in ['HP','67','ATK','90','BREAK','40','REGEN','68','57','60']), txt[:200])
        pg.select_option('#pForm', 'Highland'); pg.wait_for_timeout(100)
        check('v10 picture changes with form', pg.get_attribute('#pArt img, #pArt span', 'data-key') in ('f:emberpup--highland-form', None) and 'Highland' in pg.text_content('#pSub'), pg.inner_html('#pArt')[:200])
        check('v10 form elements shown (Fire, Earth)', pg.locator('#pElem .elc').count() == 2 and 'Earth' in pg.text_content('#pSub'), pg.text_content('#pSub'))
        pg.click('#persAxes [data-l=J]'); pg.click('#persAxes [data-l=E]'); pg.click('#persAxes [data-l=I]')
        check('v10 personality pairs are exclusive (I replaces E)', pg.input_value('#pPers') == 'IJ'.replace('IJ','I') + '' or pg.input_value('#pPers') == 'IJ', pg.input_value('#pPers'))
        check('v10 personality shown on the board', '(J)' in pg.text_content('#meta_HP') and '(I)' in pg.text_content('#meta_REGEN'), pg.text_content('#meta_HP'))
        check('v10 personality readout', pg.text_content('#persOut') == 'I··J', pg.text_content('#persOut'))
        pg.select_option('#pMode', 'goal')
        sup = pg.evaluate("GAME.aniimo.find(a=>a.released&&a.role==='Support'&&a.chart).slug")
        pg.select_option('#pA', sup); pg.wait_for_timeout(150)
        check('v10 changing Aniimo sets its goal before calculating', pg.input_value('#oGoal') == 'kit' and 'skill effects' in pg.text_content('#planKind'), pg.text_content('#planKind'))
        pg.select_option('#pMode', 'rules'); pg.select_option('#pA', 'emberpup')
        fen = pg.evaluate("GAME.aniimo.find(a=>a.name==='Fennelun').slug")
        pg.evaluate(f"pickAniimo('{fen}')"); pg.wait_for_timeout(100)
        check('v10 Fennelun says no verified chart', 'No verified stats' in pg.text_content('#pChart'))
        pg.select_option('#pA', 'emberpup'); pg.wait_for_timeout(100)
        pg.click('#grid .card >> nth=2'); pg.wait_for_timeout(150)
        check('v10 detail panel has chart and forms', pg.locator('#dlgBox .famchart').count() == 1 and pg.locator('#dlgBox .fchip').count() >= 1)
        pg.keyboard.press('Escape')
        check('v10.1 personality and game items sit under the stat bars', pg.locator('.boardextra #persAxes').count() == 1 and pg.locator('.boardextra #pItems').count() == 1 and pg.locator('#who #persAxes').count() == 0)
        pg.evaluate("$('pPers').value='EIJ';renderPers();plan()")
        check('v10.1 both letters of a pair are not applied', pg.text_content('#persOut') == '···J' and '(E)' not in pg.text_content('#meta_ATK') and '(I)' not in pg.text_content('#meta_REGEN'), pg.text_content('#persOut'))
        check('v10.1 raw stat warning next to the inputs', 'already includes personality' in pg.text_content('.rawnote'))
        h1 = pg.evaluate("document.getElementById('who').offsetHeight"); h2 = pg.evaluate("document.querySelector('.board').offsetHeight")
        check('v10.1 the two columns are close in height', abs(h1 - h2) < 0.25 * max(h1, h2), (h1, h2))
        pg.evaluate("$('pPers').value='';renderPers();plan()")
        tr = pg.evaluate("GAME.aniimo.find(a=>a.name==='Tromber').slug"); pg.select_option('#pA', tr); pg.wait_for_timeout(100)
        check('v10.2 enhanced skill off by default, Tromber caps not applied', 'inactive' in pg.text_content('#enhOut') and "aren't applied" in pg.text_content('#notes'))
        pg.select_option('#pAlpha', 'wild'); pg.wait_for_timeout(100)
        check('v10.2 wild Alpha turns it on and the caps apply', 'ACTIVE (Alpha)' in pg.text_content('#enhOut') and 'caps (ATK 800 and HP 16,000) apply' in pg.text_content('#notes'), pg.text_content('#notes')[:300])
        pg.select_option('#pAlpha', 'no'); pg.select_option('#pItem', 'h04'); pg.fill('#pItemLv', '10'); pg.select_option('#pContract', 'this'); pg.dispatch_event('#pItemLv','input'); pg.wait_for_timeout(100)
        check('v10.2 contract needs +15', 'needs a Legendary held item at +15' in pg.text_content('#enhOut'))
        pg.fill('#pItemLv', '15'); pg.dispatch_event('#pItemLv','input'); pg.wait_for_timeout(100)
        check('v10.2 contract on +15 item turns it on', 'ACTIVE (contract' in pg.text_content('#enhOut'))
        pg.select_option('#pContract', 'none'); pg.select_option('#pItem', ''); pg.select_option('#pA', 'emberpup'); pg.fill('#pLevel', '70'); pg.dispatch_event('#pLevel','input'); pg.select_option('#pRank', '7'); pg.wait_for_timeout(100)
        check('v10.2 board spells out Potential past 20', '20 (max) shown + 4 bonus = 24 effective' in pg.text_content('#meta_ATK'), pg.text_content('#meta_ATK'))
        check('v10.3 next breakpoint text', 'next ×4 at 28: out of reach' in pg.text_content('#meta_ATK'), pg.text_content('#meta_ATK'))
        pg.fill('#pLevel', '55'); pg.dispatch_event('#pLevel','input'); pg.wait_for_timeout(100)
        check('v10.3 rank lowered to 5 at level 55, 6 and 7 greyed out', pg.input_value('#pRank') == '5' and pg.evaluate("[...document.getElementById('pRank').options].filter(o=>o.disabled).map(o=>o.value).join()") == '6,7')
        check('v10.3 points summary', '0 / 25' in pg.text_content('#sumBox') and 'Most possible at Lv 55: 25' in pg.text_content('#sumBox') and '78' in pg.text_content('#sumBox'), pg.text_content('#sumBox'))
        pg.fill('#pLevel', '60'); pg.dispatch_event('#pLevel','input'); pg.select_option('#pRank', '6')
        check('v10.3 events banner shows Berylline Vale on Oct 8', 'Berylline Vale' in pg.text_content('#events') and 'Journey Chronicles' in pg.text_content('#events') and 'roadmap' in pg.text_content('#events'), pg.text_content('#events')[:300])
        pg.click('#persBest'); pg.wait_for_timeout(1500)
        check('v10.3 best personality for this setup', 'Best for this setup' in pg.text_content('#persRes') and 'Runner-up' in pg.text_content('#persRes') and 'GameWith default' in pg.text_content('#persRes'), pg.text_content('#persRes')[:300])
        best = pg.text_content('#persUse').replace('Use ','').strip(); pg.click('#persUse'); pg.wait_for_timeout(100)
        check('v10.3 "Use it" applies the personality', pg.text_content('#persOut') == best, (best, pg.text_content('#persOut')))
        pg.evaluate("$('pPers').value='';renderPers();plan()")
        # validation fix
        pg.fill('#in_ATK', '8'); pg.fill('#aq_ATK', '20'); pg.dispatch_event('#aq_ATK', 'input')
        check(f'v{ver} Innate 8 + Acquired 20 shows an error', 'caps the total at 20' in pg.inner_text('#errBox'))
        check(f'v{ver} Acquired input max follows Innate', pg.get_attribute('#aq_ATK', 'max') == '12')
        pg.fill('#aq_ATK', '0'); pg.fill('#in_ATK', '0'); pg.dispatch_event('#in_ATK', 'input')
        check(f'v{ver} error clears', pg.inner_text('#errBox').strip() == '')
        check(f'v{ver} label says game recommendation, not main pick', 'Main pick' not in pg.content() and 'Primary game recommendation' in pg.content())
        # goal mode on board
        pg.select_option('#pMode', 'goal'); pg.wait_for_timeout(100)
        check(f'v{ver} board can plan by goal', 'Calculated' in pg.inner_text('#planKind'), pg.inner_text('#planKind'))
        pg.select_option('#pMode', 'rules')
        # optimizer best tab
        pg.click('#oRun'); pg.wait_for_timeout(2500)
        txt = pg.inner_text('#oBest')
        check(f'v{ver} optimizer ranks items', pg.locator('#oBest tr.win').count() == 1 and 'Something went wrong' not in txt, txt[:200])
        if float(ver) >= 8: check(f'v{ver} shows a verdict', pg.locator('#oBest .verdict').count() == 1)
        else: check('v7 limits to Potential items (no Vanguard)', "Vanguard" not in txt)
        pg.click('#oBest [data-use]'); pg.wait_for_timeout(200)
        check(f'v{ver} "Use on board" equips item and switches to goal mode', pg.input_value('#pItem') != '' and pg.input_value('#pMode') == 'goal')
        # builds / team tabs present only from their version
        tabs = pg.locator('#oTabs button:visible').all_inner_texts()
        check(f'v{ver} tab set', ('Compare builds' in tabs) == (float(ver) >= 8) and ('Team' in tabs) == (float(ver) >= 9), tabs)
        if float(ver) >= 8:
            pg.click('#oTabs [data-t=builds]'); pg.click('#oRun'); pg.wait_for_timeout(5000)
            t2 = pg.inner_text('#oBuilds'); check(f'v{ver} build comparison runs', 'Which build leads' in t2 and 'Something went wrong' not in t2, t2[:300])
            pg.screenshot(path=str(SHOTS / f'v{ver}_builds.png'), full_page=False)
        if float(ver) >= 9:
            pg.click('#oTabs [data-t=team]'); pg.click('#oRun'); pg.wait_for_timeout(5000)
            t3 = pg.inner_text('#oTeam'); check('v10 team optimizer runs', pg.locator('#oTeam .mcard').count() == 3 and 'Something went wrong' not in t3, t3[:300])
            slot = pg.locator('#tSlots .slot3').nth(1); slot.locator('[data-k=a]').select_option(sup); slot.locator('[data-k=src]').select_option('planner')
            pg.click('#oRun'); pg.wait_for_timeout(4000)
            check('v10 team slot refuses another Aniimo\'s planner stats', 'so this slot used the defaults' in pg.inner_text('#oTeam'), pg.inner_text('#oTeam')[-300:])
            # owned mode with one Fang for three slots
            pg.click('#oTabs [data-t=inv]'); pg.fill('[data-inv=h02]', '15'); pg.dispatch_event('[data-inv=h02]', 'change')
            pg.select_option('#oItems', 'owned'); pg.click('#oTabs [data-t=team]'); pg.click('#oRun'); pg.wait_for_timeout(3000)
            n = pg.locator('#oTeam .mcard', has_text='Ferocious Fang').count()
            check('v10 owned mode hands out at most the copies owned', n <= 1, n)
            pg.select_option('#oItems', 'all')
        # saved builds
        pg.click('#oTabs [data-t=saved]'); pg.fill('#sName', 'Test build'); pg.click('#sSave')
        check(f'v{ver} build saves', pg.locator('#sList .saved').count() == 1)
        pg.fill('#pLevel', '45'); pg.dispatch_event('#pLevel', 'input')
        pg.click('#sList [data-load="0"]'); pg.wait_for_timeout(200)
        check(f'v{ver} build loads back', pg.input_value('#pLevel') == '60')
        pg.click('#sExport'); code = pg.input_value('#sCode')
        check(f'v{ver} export code made', code.startswith('ANP1.'))
        pg.click('#sImport'); check(f'v{ver} import adds the build', pg.locator('#sList .saved').count() == 2)
        # settings
        pg.select_option('#xPot', 'add'); pg.wait_for_timeout(100)
        check(f'v{ver} formula switch updates the table', '1.360' in pg.text_content('#mult'))
        check(f'v{ver} data checks all pass', 'All checks pass' in pg.text_content('#dSum'), pg.text_content('#dSum'))
        pg.reload(); pg.wait_for_timeout(300)
        check(f'v{ver} settings survive reload', pg.input_value('#xPot') == 'add')
        check(f'v{ver} no script errors after all steps', not errs, errs)
        pg.locator('#optimizer').scroll_into_view_if_needed(); pg.screenshot(path=str(SHOTS / f'v{ver}_opt.png'))
        # phone width
        pg.set_viewport_size({'width': 390, 'height': 844}); pg.wait_for_timeout(200)
        sw = pg.evaluate('document.documentElement.scrollWidth')
        check(f'v{ver} no sideways scroll on a phone', sw <= 390, sw)
        ctx.close()

    # v10.4 event themes
    def page_at(date, motion='no-preference'):
        c = b.new_context(viewport={'width': 1280, 'height': 900}, reduced_motion=motion); c.route('http*://**/*', lambda r: r.abort())
        pg = c.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
        pg.goto('file:///home/claude/work/site_v10.4/index.html' + ('?date=' + date if date else '')); pg.wait_for_timeout(300); return c, pg, errs
    c, pg, errs = page_at('2026-10-08T12:00:00-04:00')
    check('v10.4 Oct 8: Prismana leads, Windchaser mixed in', pg.evaluate("document.body.dataset.theme") == 'prismana' and 'windchaser' in pg.evaluate("document.body.dataset.sec"), pg.evaluate("[document.body.dataset.theme,document.body.dataset.sec]"))
    check('v10.4 header art and tag shown', pg.locator('#themeArt .main').count() == 1 and 'Prismana + Windchaser' in pg.text_content('#themeTag'), pg.text_content('#themeTag'))
    check('v10.4 effects drawn, behind the page and not clickable', pg.locator('#fx .fx-spark').count() >= 16 and pg.locator('#fx .fx-feather').count() >= 4 and pg.evaluate("getComputedStyle(document.getElementById('fx')).pointerEvents") == 'none')
    check('v10.4 one-line banner, details hidden until asked', pg.is_visible('#evMore') is False and 'Berylline Vale' in pg.inner_text('.evnow'))
    pg.click('#evToggle'); check('v10.4 details expand', pg.is_visible('#evMore'))
    before = pg.text_content('#spendLine') + pg.text_content('#sumBox')
    pg.select_option('#themeSel', 'glamour'); pg.wait_for_timeout(100)
    check('v10.4 manual theme pick', pg.evaluate("document.body.dataset.theme") == 'glamour' and pg.locator('#fx .fx-beam').count() == 3)
    check('v10.4 theme never changes the numbers', before == pg.text_content('#spendLine') + pg.text_content('#sumBox'))
    pg.reload(); pg.wait_for_timeout(300); check('v10.4 theme choice remembered', pg.input_value('#themeSel') == 'glamour' and pg.evaluate("document.body.dataset.theme") == 'glamour')
    pg.select_option('#themeSel', 'default'); pg.wait_for_timeout(100)
    check('v10.4 Default removes the theme', pg.evaluate("document.body.dataset.theme") is None and pg.locator('#fx *').count() == 0)
    pg.select_option('#themeSel', 'auto'); check('v10.4 no script errors', not errs, errs); c.close()
    c, pg, errs = page_at('2026-10-20T12:00:00-04:00')
    check('v10.4 Oct 20: roadmap-only Prismana does not theme automatically; Windchaser does', pg.evaluate("document.body.dataset.theme") == 'windchaser' and not pg.evaluate("document.body.dataset.sec"), pg.evaluate("[document.body.dataset.theme,document.body.dataset.sec]")); c.close()
    c, pg, errs = page_at('2026-12-20T12:00:00-05:00')
    check('v10.4 after all events: normal sky', pg.evaluate("document.body.dataset.theme") is None and 'No events on record' in pg.inner_text('.evnow')); c.close()
    c, pg, errs = page_at('2026-09-26T12:00:00-04:00')
    check('v10.4 Sep 26: Glamour Star (official) leads Windchaser', pg.evaluate("document.body.dataset.theme") == 'glamour' and pg.evaluate("document.body.dataset.sec") == 'windchaser', pg.evaluate("[document.body.dataset.theme,document.body.dataset.sec]")); c.close()
    c, pg, errs = page_at('2026-10-08T12:00:00-04:00', 'reduce')
    check('v10.4 reduced motion stops all animation', pg.evaluate("[...document.querySelectorAll('#fx *, .frame, .plate')].every(e=>getComputedStyle(e).animationName==='none')")); c.close()
    b.close()
print(f'\n{sum(res)} passed, {len(res) - sum(res)} failed')
