"""Opens each built version in Chromium and drives every feature. Prints PASS/FAIL lines."""
import sys, pathlib
from playwright.sync_api import sync_playwright
SHOTS = pathlib.Path('/tmp/claude-0/-home-claude/1a34ac8d-b6d4-5a9c-8b16-78338b6c1bbd/scratchpad')
res = []
def check(name, ok, detail=''):
    res.append(ok); print(('PASS ' if ok else 'FAIL ') + name + (('  ' + str(detail)) if detail and not ok else ''))

with sync_playwright() as p:
    b = p.chromium.launch()
    for ver in ('10.11',):
        ctx = b.new_context(viewport={'width': 1280, 'height': 900})
        ctx.route('http*://**/*', lambda r: r.abort())   # sandbox has no internet; images fall back
        pg = ctx.new_page(); errs = []
        pg.on('pageerror', lambda e: errs.append(str(e)))
        pg.goto(f'file:///home/claude/work/site_v{ver}/index.html?date=2026-10-08T12:00:00-04:00'); pg.wait_for_timeout(400)
        check(f'v{ver} loads without script errors', not errs, errs)
        check(f'v{ver} roster shows 100 cards', pg.locator('#grid .card').count() == 100)
        # v10 checks
        pg.select_option('#pA', 'emberpup'); pg.wait_for_timeout(150)
        txt = pg.text_content('#pChart')
        check('v10 chart shows Emberpup numbers', all(x in txt for x in ['HP','67','ATK','90','BREAK','40','REGEN','68','57','60']), txt[:200])
        pg.select_option('#pForm', 'Highland'); pg.wait_for_timeout(100)
        check('v10 picture changes with form', pg.get_attribute('#pArt img, #pArt span', 'data-key') in ('f:emberpup--highland-form', None) and 'Highland' in pg.text_content('#pSub'), pg.inner_html('#pArt')[:200])
        check('v10 form elements shown (Fire, Earth)', pg.locator('#pElem .elc').count() == 2 and 'Earth' in pg.text_content('#pSub'), pg.text_content('#pSub'))
        pg.click('#persAxes [data-l=J]'); pg.click('#persAxes [data-l=E]'); pg.click('#persAxes [data-l=I]')
        check('v10 personality pairs are exclusive (I replaces E)', pg.input_value('#pPers') == 'IJ'.replace('IJ','I') + '' or pg.input_value('#pPers') == 'IJ', pg.input_value('#pPers'))
        check('v10 personality shown on the board', '(J)' in pg.text_content('#meta_HP') and '(I)' in pg.text_content('#meta_REGEN'), pg.text_content('#meta_HP'))
        check('v10 personality readout', pg.text_content('#persOut') == 'I··J', pg.text_content('#persOut'))
        pg.select_option('#pMode', 'goal')
        sup = pg.evaluate("GAME.aniimo.find(a=>a.released&&a.role==='Support'&&a.chart).slug")
        pg.select_option('#pA', sup); pg.wait_for_timeout(150)
        check('v10 changing Aniimo sets its goal before calculating', pg.input_value('#oGoal') == 'kit' and 'skill effects' in pg.text_content('#planKind'), pg.text_content('#planKind'))
        pg.select_option('#pMode', 'rules'); pg.select_option('#pA', 'emberpup')
        fen = pg.evaluate("GAME.aniimo.find(a=>a.name==='Fennelun').slug")
        pg.evaluate(f"pickAniimo('{fen}')"); pg.wait_for_timeout(100)
        check('v10 Fennelun says no verified chart', 'No verified stats' in pg.text_content('#pChart'))
        pg.select_option('#pA', 'emberpup'); pg.wait_for_timeout(100)
        pg.click('#grid .card >> nth=2'); pg.wait_for_timeout(150)
        check('v10 detail panel has chart and forms', pg.locator('#dlgBox .famchart').count() == 1 and pg.locator('#dlgBox .fchip').count() >= 1)
        pg.keyboard.press('Escape')
        check('v10.1 personality and game items sit under the stat bars', pg.locator('.boardextra #persAxes').count() == 1 and pg.locator('.boardextra #pItems').count() == 1 and pg.locator('#who #persAxes').count() == 0)
        pg.evaluate("$('pPers').value='EIJ';renderPers();plan()")
        check('v10.1 both letters of a pair are not applied', pg.text_content('#persOut') == '···J' and '(E)' not in pg.text_content('#meta_ATK') and '(I)' not in pg.text_content('#meta_REGEN'), pg.text_content('#persOut'))
        check('v10.1 raw stat warning next to the inputs', 'already includes personality' in pg.text_content('.rawnote'))
        h1 = pg.evaluate("document.getElementById('who').offsetHeight"); h2 = pg.evaluate("document.querySelector('.board').offsetHeight")
        check('v10.1 the two columns are close in height', abs(h1 - h2) < 0.25 * max(h1, h2), (h1, h2))
        pg.evaluate("$('pPers').value='';renderPers();plan()")
        tr = pg.evaluate("GAME.aniimo.find(a=>a.name==='Tromber').slug"); pg.select_option('#pA', tr); pg.wait_for_timeout(100)
        check('v10.2 enhanced skill off by default, Tromber caps not applied', 'inactive' in pg.text_content('#enhOut') and "aren't applied" in pg.text_content('#notes'))
        pg.select_option('#pAlpha', 'wild'); pg.wait_for_timeout(100)
        check('v10.2 wild Alpha turns it on and the caps apply', 'ACTIVE (Alpha)' in pg.text_content('#enhOut') and 'caps (ATK 800 and HP 16,000) apply' in pg.text_content('#notes'), pg.text_content('#notes')[:300])
        pg.select_option('#pAlpha', 'no'); pg.select_option('#pItem', 'h04'); pg.fill('#pItemLv', '10'); pg.select_option('#pContract', 'this'); pg.dispatch_event('#pItemLv','input'); pg.wait_for_timeout(100)
        check('v10.2 contract needs +15', 'needs a Legendary held item at +15' in pg.text_content('#enhOut'))
        pg.fill('#pItemLv', '15'); pg.dispatch_event('#pItemLv','input'); pg.wait_for_timeout(100)
        check('v10.2 contract on +15 item turns it on', 'ACTIVE (contract' in pg.text_content('#enhOut'))
        pg.select_option('#pContract', 'none'); pg.select_option('#pItem', ''); pg.select_option('#pA', 'emberpup'); pg.fill('#pLevel', '70'); pg.dispatch_event('#pLevel','input'); pg.select_option('#pRank', '7'); pg.wait_for_timeout(100)
        check('v10.2 board spells out Potential past 20', '20 (max) shown + 4 bonus = 24 effective' in pg.text_content('#meta_ATK'), pg.text_content('#meta_ATK'))
        check('v10.3 next breakpoint text', 'next ×4 at 28: out of reach' in pg.text_content('#meta_ATK'), pg.text_content('#meta_ATK'))
        pg.fill('#pLevel', '55'); pg.dispatch_event('#pLevel','input'); pg.wait_for_timeout(100)
        check('v10.3 rank lowered to 5 at level 55, 6 and 7 greyed out', pg.input_value('#pRank') == '5' and pg.evaluate("[...document.getElementById('pRank').options].filter(o=>o.disabled).map(o=>o.value).join()") == '6,7')
        check('v10.3 points summary', '0 / 25' in pg.text_content('#sumBox') and 'Most possible at Lv 55: 25' in pg.text_content('#sumBox') and '78' in pg.text_content('#sumBox'), pg.text_content('#sumBox'))
        pg.fill('#pLevel', '60'); pg.dispatch_event('#pLevel','input'); pg.select_option('#pRank', '6')
        pg.click('#persBest'); pg.wait_for_timeout(1500)
        check('v10.3 best personality for this setup', 'Best for this setup' in pg.text_content('#persRes') and 'Runner-up' in pg.text_content('#persRes') and 'GameWith default' in pg.text_content('#persRes'), pg.text_content('#persRes')[:300])
        best = pg.text_content('#persUse').replace('Use ','').strip(); pg.click('#persUse'); pg.wait_for_timeout(100)
        check('v10.3 "Use it" applies the personality', pg.text_content('#persOut') == best, (best, pg.text_content('#persOut')))
        pg.evaluate("$('pPers').value='';renderPers();plan()")
        # validation fix
        pg.fill('#in_ATK', '8'); pg.fill('#aq_ATK', '20'); pg.dispatch_event('#aq_ATK', 'input')
        check(f'v{ver} Innate 8 + Acquired 20 shows an error', 'caps the total at 20' in pg.inner_text('#errBox'))
        check(f'v{ver} Acquired input max follows Innate', pg.get_attribute('#aq_ATK', 'max') == '12')
        pg.fill('#aq_ATK', '0'); pg.fill('#in_ATK', '0'); pg.dispatch_event('#in_ATK', 'input')
        check(f'v{ver} error clears', pg.inner_text('#errBox').strip() == '')
        check(f'v{ver} label says game recommendation, not main pick', 'Main pick' not in pg.content() and 'Primary game recommendation' in pg.content())
        # goal mode on board
        pg.select_option('#pMode', 'goal'); pg.wait_for_timeout(100)
        check(f'v{ver} board can plan by goal', 'Calculated' in pg.inner_text('#planKind'), pg.inner_text('#planKind'))
        pg.select_option('#pMode', 'rules')
        # optimizer best tab
        pg.click('#oRun'); pg.wait_for_timeout(2500)
        txt = pg.inner_text('#oBest')
        check(f'v{ver} optimizer ranks items', pg.locator('#oBest tr.win').count() == 1 and 'Something went wrong' not in txt, txt[:200])
        if float(ver) >= 8: check(f'v{ver} shows a verdict', pg.locator('#oBest .verdict').count() == 1)
        else: check('v7 limits to Potential items (no Vanguard)', "Vanguard" not in txt)
        pg.click('#oBest [data-use]'); pg.wait_for_timeout(200)
        check(f'v{ver} "Use on board" equips item and switches to goal mode', pg.input_value('#pItem') != '' and pg.input_value('#pMode') == 'goal')
        # builds / team tabs present only from their version
        tabs = pg.locator('#oTabs button:visible').all_inner_texts()
        check(f'v{ver} tab set', ('Compare builds' in tabs) == (float(ver) >= 8) and ('Team' in tabs) == (float(ver) >= 9), tabs)
        if float(ver) >= 8:
            pg.click('#oTabs [data-t=builds]'); pg.click('#oRun'); pg.wait_for_timeout(5000)
            t2 = pg.inner_text('#oBuilds'); check(f'v{ver} build comparison runs', 'Which build leads' in t2 and 'Something went wrong' not in t2, t2[:300])
            pg.screenshot(path=str(SHOTS / f'v{ver}_builds.png'), full_page=False)
        if float(ver) >= 9:
            pg.click('#oTabs [data-t=team]'); pg.click('#oRun'); pg.wait_for_timeout(5000)
            t3 = pg.inner_text('#oTeam'); check('v10.11 team optimizer runs with 4 Aniimo', pg.locator('#oTeam .mcard').count() == 4 and 'Something went wrong' not in t3, t3[:300])
            slot = pg.locator('#tSlots .slot3').nth(1); slot.locator('[data-k=a]').select_option(sup); slot.locator('[data-k=src]').select_option('planner')
            pg.click('#oRun'); pg.wait_for_timeout(4000)
            check('v10 team slot refuses another Aniimo\'s planner stats', 'so this slot used the defaults' in pg.inner_text('#oTeam'), pg.inner_text('#oTeam')[-300:])
            # owned mode with one Fang for three slots
            pg.click('#oTabs [data-t=inv]'); pg.fill('[data-inv=h02]', '15'); pg.dispatch_event('[data-inv=h02]', 'change')
            pg.select_option('#oItems', 'owned'); pg.click('#oTabs [data-t=team]'); pg.click('#oRun'); pg.wait_for_timeout(3000)
            n = pg.locator('#oTeam .mcard', has_text='Ferocious Fang').count()
            check('v10 owned mode hands out at most the copies owned', n <= 1, n)
            pg.select_option('#oItems', 'all')
        # saved builds
        pg.click('#oTabs [data-t=saved]'); pg.fill('#sName', 'Test build'); pg.click('#sSave')
        check(f'v{ver} build saves', pg.locator('#sList .saved').count() == 1)
        pg.fill('#pLevel', '45'); pg.dispatch_event('#pLevel', 'input')
        pg.click('#sList [data-load="0"]'); pg.wait_for_timeout(200)
        check(f'v{ver} build loads back', pg.input_value('#pLevel') == '60')
        pg.click('#sExport'); code = pg.input_value('#sCode')
        check(f'v{ver} export code made', code.startswith('ANP1.'))
        pg.click('#sImport'); check(f'v{ver} import adds the build', pg.locator('#sList .saved').count() == 2)
        # settings
        pg.select_option('#xPot', 'add'); pg.wait_for_timeout(100)
        check(f'v{ver} formula switch updates the table', '1.360' in pg.text_content('#mult'))
        check(f'v{ver} data checks all pass', 'All checks pass' in pg.text_content('#dSum'), pg.text_content('#dSum'))
        pg.reload(); pg.wait_for_timeout(300)
        check(f'v{ver} settings survive reload', pg.input_value('#xPot') == 'add')
        check(f'v{ver} no script errors after all steps', not errs, errs)
        pg.locator('#optimizer').scroll_into_view_if_needed(); pg.screenshot(path=str(SHOTS / f'v{ver}_opt.png'))
        # phone width
        pg.set_viewport_size({'width': 390, 'height': 844}); pg.wait_for_timeout(200)
        sw = pg.evaluate('document.documentElement.scrollWidth')
        check(f'v{ver} no sideways scroll on a phone', sw <= 390, sw)
        ctx.close()

    # v10.6 event themes and portrait trimming
    def page_at(date, motion='no-preference'):
        c = b.new_context(viewport={'width': 1280, 'height': 900}, reduced_motion=motion); c.route('http*://**/*', lambda r: r.abort() if 'localhost' not in r.request.url else r.continue_())
        pg = c.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
        pg.goto('file:///home/claude/work/site_v10.11/index.html' + ('?date=' + date if date else '')); pg.wait_for_timeout(300); return c, pg, errs
    c, pg, errs = page_at('2026-10-08T12:00:00-04:00')
    check('v10.6 Oct 8: Windchaser leads, Prismana is the accent', pg.evaluate("document.body.dataset.theme") == 'windchaser' and pg.evaluate("document.body.dataset.sec") == 'prismana', pg.evaluate("[document.body.dataset.theme,document.body.dataset.sec]"))
    check('v10.7 Subtle event layer: petals and wind, at most 5 + 2 accent pieces', pg.locator('#fx .fx-petal').count() >= 2 and pg.locator('#fx .fx-streak').count() >= 1 and pg.locator('#fx > *:not(.fx-glow)').count() <= 7, pg.locator('#fx > *').count())
    check('v10.6 no events line on the page', pg.locator('#events').count() == 0)
    check('v10.6 header art box sits inside the header', pg.evaluate("(()=>{const i=document.querySelector('.intro').getBoundingClientRect(),a=document.getElementById('themeArt').getBoundingClientRect();return a.top>=i.top&&a.bottom<=i.bottom&&a.right<=i.right})()"))
    before = pg.text_content('#spendLine') + pg.text_content('#sumBox')
    pg.click("summary:has-text('Look')"); pg.select_option('#xTheme', 'glamour'); pg.wait_for_timeout(100)
    check('v10.6 Theme picker in Settings works', pg.evaluate("document.body.dataset.theme") == 'glamour')
    check('v10.6 theme never changes the numbers', before == pg.text_content('#spendLine') + pg.text_content('#sumBox'))
    pg.reload(); pg.wait_for_timeout(300); check('v10.6 theme choice remembered', pg.input_value('#xTheme') == 'glamour')
    pg.click("summary:has-text('Look')"); pg.select_option('#xTheme', 'default'); check('v10.6 Default removes the theme', pg.evaluate("document.body.dataset.theme") is None and pg.locator('#fx *').count() == 0)
    pg.select_option('#xTheme', 'auto'); check('v10.6 no script errors', not errs, errs); c.close()
    c, pg, errs = page_at('2026-10-20T12:00:00-04:00')
    check('v10.6 Oct 20: roadmap-only Prismana does not theme; Windchaser alone', pg.evaluate("document.body.dataset.theme") == 'windchaser' and not pg.evaluate("document.body.dataset.sec")); c.close()
    c, pg, errs = page_at('2026-10-08T12:00:00-04:00'); pg.evaluate("GAME.events.list.find(e=>e.name.startsWith('Vein Abundance: Berylline')).featured=true;applyTheme()")
    check('v10.6 a featured event leads even when shorter', pg.evaluate("document.body.dataset.theme") == 'prismana' and pg.evaluate("document.body.dataset.sec") == 'windchaser'); c.close()
    c, pg, errs = page_at('2026-12-20T12:00:00-05:00')
    check('v10.6 after all events: normal sky', pg.evaluate("document.body.dataset.theme") is None); c.close()
    c, pg, errs = page_at('2026-09-26T12:00:00-04:00')
    check('v10.6 Sep 26: Windchaser leads, Glamour Star accent', pg.evaluate("[document.body.dataset.theme,document.body.dataset.sec].join()") == 'windchaser,glamour'); c.close()
    c, pg, errs = page_at('2026-10-08T12:00:00-04:00', 'reduce')
    check('v10.6 reduced motion stops all animation', pg.evaluate("[...document.querySelectorAll('#fx *, .frame, .plate')].every(e=>getComputedStyle(e).animationName==='none')")); c.close()
    # trimming: serve a copy over http with padded test portraits
    import subprocess, shutil, os, time
    from PIL import Image, ImageDraw
    T = '/tmp/claude-0/-home-claude/1a34ac8d-b6d4-5a9c-8b16-78338b6c1bbd/scratchpad/trimtest'; shutil.rmtree(T, ignore_errors=True); shutil.copytree('/home/claude/work/site_v10.11', T); os.makedirs(T + '/images', exist_ok=True)
    def mk(n, W, H, box):
        im = Image.new('RGBA', (W, H), (0, 0, 0, 0)); ImageDraw.Draw(im).ellipse(box, fill=(200, 80, 160, 255)); im.save(T + '/images/' + n, 'PNG')
    mk('p_inferlupa.webp', 1000, 1000, (380, 420, 620, 580)); Image.new('RGBA', (600, 1200), (230, 90, 40, 255)).save(T + '/images/p_flameruff.webp', 'PNG'); mk('p_emberpup.webp', 800, 800, (100, 100, 700, 700))
    srv = subprocess.Popen(['python3', '-m', 'http.server', '8765', '--bind', '127.0.0.1', '-d', T], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL); time.sleep(1)
    try:
        c = b.new_context(viewport={'width': 1280, 'height': 900}); c.route('**/*', lambda r: r.continue_() if '127.0.0.1' in r.request.url else r.abort())
        pg = c.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
        sizes = {}
        for slug in ('inferlupa', 'flameruff', 'emberpup'):
            pg.goto('http://127.0.0.1:8765/index.html'); pg.wait_for_timeout(400); pg.select_option('#pA', slug); pg.wait_for_timeout(600)
            sizes[slug] = pg.evaluate("(()=>{const i=document.querySelector('#pArt img');return [i.src.startsWith('data:'),i.naturalWidth,i.naturalHeight]})()")
        check('v10.6 padded portrait gets trimmed (Inferlupa test image)', sizes['inferlupa'][0] and sizes['inferlupa'][1] < 400, sizes)
        check('v10.6 a portrait with no empty space is left alone', not sizes['flameruff'][0], sizes)
        check('v10.6 trimming causes no script errors', not errs, errs); c.close()
    finally:
        srv.terminate()
    # v10.7 Living Idyll
    ANIM = "(()=>{let n=0;document.querySelectorAll('#scene *, #fx *, #roam *').forEach(e=>{const s=getComputedStyle(e);if(s.animationName!=='none'&&s.display!=='none'&&e.closest('svg')===null)n++});return n+document.querySelectorAll('#scene .bloom.pulse').length})()"
    def look(vis=None, tod=None, date='2026-10-08T12:00:00-04:00', hour=None, w=1600, motion='no-preference', drawn=False):
        c = b.new_context(viewport={'width': w, 'height': 900}, reduced_motion=motion); c.route('http*://**/*', lambda r: r.abort())
        pg = c.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
        pg.goto('file:///home/claude/work/site_v10.11/index.html?date=' + date + ('&hour=' + str(hour) if hour is not None else '')); pg.wait_for_timeout(200)
        if vis: pg.evaluate(f"localStorage.setItem('aniimo.visual.v1',JSON.stringify('{vis}'))")
        if tod: pg.evaluate(f"localStorage.setItem('aniimo.tod.v1',JSON.stringify('{tod}'))")
        if vis or tod: pg.reload(); pg.wait_for_timeout(300)
        if drawn: pg.evaluate("GAME.scene.art=null;renderScene();applyTheme()")
        return c, pg, errs
    for vis, cap in (('full', 48), ('subtle', 16), ('minimal', 0), ('off', 0)):
        for hour in (12, 23):
            c, pg, errs = look(vis if vis != 'subtle' else None, hour=hour); n = pg.evaluate(ANIM)
            check(f'v10.7 {vis} at {hour}:00: {n} moving things, cap {cap}', n <= cap and (n > 0) == (cap > 0), n)
            if vis == 'subtle' and hour == 12: check('v10.7 Subtle is the default', pg.evaluate("document.body.dataset.vis") == 'subtle')
            if vis == 'minimal' and hour == 12: check('v10.9 Minimal keeps the picture and still petals, no twinkles or shooting stars', pg.locator('#scene .sky.art').count() == 1 and pg.locator('#fx .still').count() >= 1 and pg.locator('#scene .tw, #scene .shoot').count() == 0)
            if vis == 'off' and hour == 12: check('v10.7 Off: no scenery, no effects', pg.evaluate("document.getElementById('scene').hidden") and pg.locator('#fx *').count() == 0)
            if vis == 'off' and hour == 23: check('v10.7 Off: no night styling', not pg.evaluate("document.body.classList.contains('night')"))
            check(f'v10.7 {vis} {hour}:00 no script errors', not errs, errs); c.close()
    c, pg, errs = look(hour=12, drawn=True); check('v10.7 drawn landscape: noon is day', not pg.evaluate("document.body.classList.contains('night')") and pg.evaluate("getComputedStyle(document.getElementById('scene')).getPropertyValue('--sk1').trim()") == '#8fd3ff'); c.close()
    c, pg, errs = look(hour=23, drawn=True); check('v10.7 drawn landscape: 23:00 is night, sky not black', pg.evaluate("document.body.classList.contains('night')") and pg.evaluate("getComputedStyle(document.getElementById('scene')).getPropertyValue('--sk1').trim()") == '#3b5293'); c.close()
    c, pg, errs = look(hour=19, drawn=True); check('v10.7 drawn landscape: 19:00 is a blend (dusk)', pg.evaluate("getComputedStyle(document.getElementById('scene')).getPropertyValue('--sk1').trim()") not in ('#8fd3ff', '#3b5293')); c.close()
    c, pg, errs = look(tod='day', hour=23, drawn=True); check('v10.7 drawn landscape: "Always day" overrides the clock', not pg.evaluate("document.body.classList.contains('night')")); c.close()
    c, pg, errs = look(hour=23, motion='reduce'); check('v10.7 reduced motion: nothing moves', pg.evaluate(ANIM) == 0); check('v10.7 reduced motion: no wanderers', pg.evaluate("roamNow()") is False); c.close()
    c, pg, errs = look(w=390); n = pg.evaluate(ANIM); check(f'v10.9 phone: {n} moving things, cap 10, no wanderers, no sideways scroll', n <= 10 and pg.evaluate("roamNow()") is False and pg.evaluate("document.documentElement.scrollWidth") <= 390, n); c.close()
    c, pg, errs = look(w=1600)
    check('v10.7 a wanderer appears in the side margin, clear of the page', pg.evaluate("roamNow(true)") and pg.evaluate("(()=>{const r=document.querySelector('#roam .roamer').getBoundingClientRect(),w=document.querySelector('.wrap').getBoundingClientRect();return r.right<=w.left||r.left>=w.right})()"))
    check('v10.7 decoration layers never take clicks', pg.evaluate("['scene','fx','roam'].every(id=>getComputedStyle(document.getElementById(id)).pointerEvents==='none')"))
    check('v10.7 Subtle keeps one wanderer at a time', pg.evaluate("roamNow()") is False and pg.locator('#roam .roamer').count() == 1)
    before = pg.text_content('#spendLine') + pg.text_content('#sumBox')
    pg.focus('#pLevel'); pg.wait_for_timeout(100); check('v10.7 typing in the planner calms the scenery', pg.evaluate("document.body.classList.contains('calm')"))
    pg.evaluate("document.activeElement.blur()"); pg.wait_for_timeout(1800); check('v10.7 calm lifts after you stop', not pg.evaluate("document.body.classList.contains('calm')"))
    pg.click("summary:has-text('Look')")
    for v in ('full', 'minimal', 'off', 'subtle'): pg.select_option('#xVis', v); pg.wait_for_timeout(80)
    pg.select_option('#xTod', 'night'); pg.wait_for_timeout(80)
    check('v10.7 visual settings never change the numbers', before == pg.text_content('#spendLine') + pg.text_content('#sumBox'))
    check('v10.7 prismana panel borders stay still', True)
    check('v10.7 no script errors', not errs, errs); c.close()
    # v10.11
    c = b.new_context(viewport={'width': 1400, 'height': 1000}); c.route('http*://**/*', lambda r: r.abort()); pg = c.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto('file:///home/claude/work/site_v10.11/index.html'); pg.wait_for_timeout(400)
    pg.click('#tlSlots [data-delslot="3"]'); pg.wait_for_timeout(100)
    check('v10.11 remove a Team Lab slot (4 to 3), add button appears', pg.locator('#tlSlots .tl-slot[data-slot]').count() == 3 and pg.locator('#tlAddSlot').count() == 1)
    pg.click('#tlAddSlot'); pg.wait_for_timeout(100); check('v10.11 add it back (3 to 4), no add button at 4', pg.locator('#tlSlots .tl-slot[data-slot]').count() == 4 and pg.locator('#tlAddSlot').count() == 0)
    check('v10.11 move element column', pg.locator('#tlSlots [data-m=element]').count() > 5)
    pg.evaluate("TL.slots[0].moves=[{name:'Big',kind:'Physical',might:50,hits:1,ep:60,cooldown:0,buff:{}}];TL.slots[1].moves=[{name:'Big2',kind:'Physical',might:50,hits:1,ep:60,cooldown:0,buff:{}}];TL.actions=[{slot:0,move:0,wait:0,state:'normal'},{slot:1,move:0,wait:1,state:'normal'}];TL.startEP=100;tlSave();tlRenderTeam();tlRenderActs();tlRenderTarget()")
    pg.click('#tlTabs [data-t=fight]'); pg.click('#tlRun'); pg.wait_for_timeout(200); lg = pg.inner_text('#tlLog')
    check('v10.11 shared team EP: the second 60-EP move is refused (40 left)', 'Not enough team EP (40 of 60)' in lg and 'Team EP' in lg and '100 → 40' in lg, lg[:400])
    pg.click('#tlTabs [data-t=fight]'); pg.select_option('#tlAlpha', 'Alpha Rookey'); pg.wait_for_timeout(100); info = pg.inner_text('#tlTarget')
    check('v10.11 Alpha picker fills name, place, element and level', 'Russet Highlands' in info and pg.input_value('[data-t=level]') == '45' and pg.input_value('[data-t=name]') == 'Alpha Rookey' and 'unverified' in info, info[:300])
    pg.fill('[data-t=hp]', '123456'); pg.dispatch_event('[data-t=hp]', 'change'); pg.fill('[data-t=def]', '321'); pg.dispatch_event('[data-t=def]', 'change'); pg.click('#tlSaveMeasure'); pg.wait_for_timeout(100)
    check('v10.11 measurement saved for this Alpha and level', 'your measurement' in pg.inner_text('#tlTarget'))
    pg.fill('[data-t=hp]', '1'); pg.dispatch_event('[data-t=hp]', 'change'); pg.select_option('#tlAlpha', 'Alpha Geoclaw'); pg.select_option('#tlAlpha', 'Alpha Rookey'); pg.wait_for_timeout(100)
    check('v10.11 picking the Alpha again reloads your measurement', pg.input_value('[data-t=hp]') == '123456' and pg.input_value('[data-t=def]') == '321')
    pg.click('#tlRun'); pg.wait_for_timeout(100); pg.locator('#tlLog [data-why]').nth(0).click()
    check('v10.11 the log labels DEF as your measurement', 'your measurement' in pg.inner_text('#tlLog'))
    pg.evaluate("document.querySelector('#oTabs [data-t=team]').click()"); pg.locator('#tSlots .slot3').nth(3).locator('[data-k=a]').select_option(''); pg.click('#oRun'); pg.wait_for_timeout(5000)
    check('v10.11 optimizer: an empty slot makes a 3-Aniimo team; search is exhaustive', pg.locator('#oTeam .mcard').count() == 3 and 'Every combination of items was checked' in pg.inner_text('#oTeam'), pg.inner_text('#oTeam')[-300:])
    check('v10.11 no script errors', not errs, errs); c.close()
    # v10.10
    c = b.new_context(viewport={'width': 1400, 'height': 1000}); c.route('http*://**/*', lambda r: r.abort()); pg = c.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto('file:///home/claude/work/site_v10.11/index.html'); pg.wait_for_timeout(400); pg.click('#tlTabs [data-t=fight]'); pg.click('#tlRun'); pg.wait_for_timeout(200)
    check('v10.10 runs with unlisted EP or cooldown are labelled incomplete', 'incomplete' in pg.inner_text('#tlLog .verdict') and 'cooldown' in pg.inner_text('#tlLog .verdict'))
    pg.click('#tlTabs [data-t=fight]'); pg.evaluate("TL.target.def=-5;tlRun()"); pg.wait_for_timeout(100)
    check('v10.10 an impossible setup is refused before simulating', 'Fix the setup first' in pg.inner_text('#tlLog'), pg.inner_text('#tlLog')[:200])
    pg.evaluate("TL.target.def=500;tlSave()"); pg.click('#tlTabs [data-t=fight]'); pg.fill('[data-t=breakMult]', ''); pg.dispatch_event('[data-t=breakMult]', 'change')
    check('v10.10 a blank BREAK multiplier stays blank (no change), not 0', pg.evaluate("TL.target.breakMult") is None)
    pg.click('#tlRun'); pg.wait_for_timeout(100); pg.click('#tlTabs [data-t=reports]'); pg.click('#tlRecord'); pg.wait_for_timeout(200)
    check('v10.10 report shows its setup code and the incomplete label', 'Setup' in pg.inner_text('#tlRepView') and 'incomplete' in pg.inner_text('#tlRepView'))
    check('v10.10 no script errors', not errs, errs); c.close()
    # v10.9 background picture
    c, pg, errs = look()
    check('v10.9 background picture set and found', 'idyll-night.webp' in pg.evaluate("getComputedStyle(document.querySelector('#scene .sky')).backgroundImage") and pg.evaluate("new Promise(r=>{const i=new Image();i.onload=()=>r(i.naturalWidth);i.onerror=()=>r(0);i.src='data/art/idyll-night.webp'})") == 1672)
    check('v10.11 Subtle: 4 twinkles, 1 shooting star, 2 fireflies, 2 rising motes', pg.locator('#scene .tw').count() == 4 and pg.locator('#scene .shoot').count() == 1 and pg.locator('#scene .firefly').count() == 2 and pg.locator('#scene .mote2').count() == 2)
    check('v10.9 drawn hills and sun are off with the picture', pg.locator('#scene .land, #scene .sun').count() == 0)
    check('v10.9 light text outside panels on the dark picture', pg.evaluate("document.body.classList.contains('night')") and pg.evaluate("getComputedStyle(document.querySelector('.sechead p')).color") == 'rgb(244, 247, 255)')
    check('v10.9 no script errors', not errs, errs); c.close()
    c, pg, errs = look(vis='full'); check('v10.9 Full: 14 twinkles, 2 shooting stars', pg.locator('#scene .tw').count() == 14 and pg.locator('#scene .shoot').count() == 2); c.close()
    c, pg, errs = look(w=390); check('v10.9 phone uses the small picture', 'idyll-night-small.webp' in pg.evaluate("getComputedStyle(document.querySelector('#scene .sky')).backgroundImage")); c.close()
    # v10.8 Team Lab
    c = b.new_context(viewport={'width': 1400, 'height': 1000}); c.route('http*://**/*', lambda r: r.abort())
    pg = c.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto('file:///home/claude/work/site_v10.11/index.html?date=2026-10-08T12:00:00-04:00'); pg.wait_for_timeout(400)
    check('v10.11 Team Lab: 4 slots with checked moves for Stellarys, Rookey, Fragrancier', pg.locator('#tlSlots .tl-slot[data-slot]').count() == 4 and 'Shooting Stars' in pg.inner_html('#tlSlots') and 'Secret Fragrance Mark' in pg.inner_html('#tlSlots'))
    plan_before = pg.text_content('#spendLine') + pg.text_content('#sumBox')
    pg.select_option('#pA', 'emberpup'); pg.fill('#rw_ATK', '1200'); pg.dispatch_event('#rw_ATK', 'input'); pg.select_option('#pItem', 'h02'); pg.fill('#pItemLv', '15'); pg.dispatch_event('#pItemLv', 'input')
    pg.evaluate("document.querySelector('#oTabs [data-t=saved]').click()"); pg.fill('#sName', 'Ember test'); pg.click('#sSave'); pg.wait_for_timeout(200)
    slot = pg.locator('#tlSlots .tl-slot').nth(0); slot.locator('[data-f=src]').select_option(label='Saved: Ember test'); pg.wait_for_timeout(200)
    s0 = pg.locator('#tlSlots .tl-slot').nth(0).inner_text()
    check('v10.8 a saved build loads into a slot (Aniimo, item and stats come along)', 'Emberpup' in s0 and 'Saved: Ember test' in s0 and 'Ferocious Fang +15' in s0 and 'attack 1310' in s0, s0[:400])  # 1200 x M(4)/M(2) (Fang +15 adds 2 ATK Potential) + 42 flat ATK
    pg.locator('#tlSlots .tl-slot').nth(1).locator('[data-f=src]').select_option('planner'); pg.wait_for_timeout(200)
    check('v10.8 "Planner" source uses the planner\'s Aniimo', 'Emberpup' in pg.locator('#tlSlots .tl-slot').nth(1).inner_text())
    pg.locator('#tlSlots .tl-slot').nth(1).locator('[data-f=src]').select_option('manual'); pg.locator('#tlSlots .tl-slot').nth(1).locator('[data-f=slug]').select_option('rookey'); pg.wait_for_timeout(200)
    pg.click('#tlTabs [data-t=fight]'); pg.fill('[data-t=breakMult]', '1.5'); pg.dispatch_event('[data-t=breakMult]', 'change')
    pg.locator('#tlActs [data-a="1"] [data-k=state]').select_option('break'); pg.wait_for_timeout(100)
    pg.click('#tlRun'); pg.wait_for_timeout(300)
    log = pg.inner_text('#tlLog')
    check('v10.8 simulation runs and logs every hit', pg.locator('#tlLog .tl-log tr').count() > 3 and 'Emberpup' in log and 'BREAK' in log and 'experimental' in log, log[:300])
    pg.locator('#tlLog [data-why]').nth(0).click(); w = pg.inner_text('#tlLog')
    check('v10.8 "Why" lists every modifier with its confidence', 'Alpha / wild ×0.625' in w and 'Model A' in w and 'verified' in w and 'assumption' in w)
    totA = pg.text_content('#tlLog .verdict h4'); pg.click('#tlTabs [data-t=fight]'); pg.select_option('#tlM', 'B'); pg.click('#tlRun'); pg.wait_for_timeout(200)
    check('v10.8 switching the Might model changes the result and is labelled', pg.text_content('#tlLog .verdict h4') != totA and 'Model B' in pg.text_content('#tlLog .verdict'))
    pg.click('#tlTabs [data-t=reports]'); pg.fill('#tlRepLabel', 'Test 1'); pg.click('#tlRecord'); pg.wait_for_timeout(200)
    check('v10.8 a run is recorded as a report', 'Test 1' in pg.inner_text('#tlRepSel') and pg.locator('#tlRepView [data-st]').count() > 0)
    pred = pg.locator('#tlRepView [data-st]').nth(0).locator('td').nth(6).inner_text().replace(',', '')
    inp = pg.locator('#tlRepView [data-st] [data-o=observed]').nth(0); inp.fill(pred); inp.dispatch_event('change'); pg.wait_for_timeout(200)
    check('v10.8 observed damage equal to the prediction is a match', '1 match' in pg.inner_text('#tlRepView'), pg.inner_text('#tlRepView')[:300])
    inp = pg.locator('#tlRepView [data-st] [data-o=observed]').nth(1); inp.fill('1'); inp.dispatch_event('change'); pg.wait_for_timeout(200)
    check('v10.8 a far-off observation is flagged', '1 off' in pg.inner_text('#tlRepView'))
    check('v10.8 report records the BREAK state of each hit', 'BREAK' in pg.inner_text('#tlRepView'))
    pg.click('#tlExpCsv'); check('v10.8 CSV export (with setup code and complete flag)', pg.input_value('#tlIO').startswith('report,setup,complete,model,mightTotal'))
    pg.click('#tlExpJson'); js = pg.input_value('#tlIO'); pg.click('#tlImport'); check('v10.8 importing the same report twice is refused', 'already here' in pg.text_content('#tlRepMsg'))
    pg.fill('#tlIO', js.replace('"id":"run-', '"id":"run-copy-')); pg.click('#tlImport'); pg.wait_for_timeout(200); check('v10.8 import works and recalculates', 'Imported' in pg.text_content('#tlRepMsg') and pg.locator('#tlRepSel option').count() == 2)
    pg.fill('#tlIO', '{"schema":2}'); pg.click('#tlImport'); check('v10.8 a broken report is rejected', "Couldn't import" in pg.text_content('#tlRepMsg'))
    pg.reload(); pg.wait_for_timeout(400); check('v10.8 team and reports survive a reload', 'Emberpup' in pg.locator('#tlSlots .tl-slot').nth(0).inner_text() and pg.evaluate("JSON.parse(localStorage.getItem('aniimo.reports.v2')).length") == 2)
    pg.select_option('#pA', 'emberpup'); pg.fill('#rw_ATK', ''); pg.dispatch_event('#rw_ATK', 'input'); pg.select_option('#pItem', ''); pg.wait_for_timeout(100)
    check('v10.8 Team Lab never changes the planner\'s numbers', plan_before == pg.text_content('#spendLine') + pg.text_content('#sumBox'))
    check('v10.8 no script errors', not errs, errs); c.close()
    c = b.new_context(viewport={'width': 390, 'height': 844}); c.route('http*://**/*', lambda r: r.abort()); pg = c.new_page(); pg.goto('file:///home/claude/work/site_v10.11/index.html'); pg.wait_for_timeout(300)
    pg.click('#tlTabs [data-t=fight]'); pg.click('#tlRun'); pg.wait_for_timeout(200)
    check('v10.8 phone: Team Lab fits, no sideways page scroll', pg.evaluate("document.documentElement.scrollWidth") <= 390, pg.evaluate("document.documentElement.scrollWidth")); c.close()
    b.close()
print(f'\n{sum(res)} passed, {len(res) - sum(res)} failed')
