/* Run with: node tests/combat.test.js (from the site folder) */
global.window = {};
const assert = require('assert');
const GAME = require('../data/game-data.js');
const E = require('../js/engine.js').init(GAME), C = require('../js/combat.js'), R = require('../js/reports.js');
let pass = 0, fail = 0; const t = (n, f) => { try { f(); pass++; console.log('ok   ' + n); } catch (e) { fail++; console.log('FAIL ' + n + '\n     ' + e.message); } };
const near = (a, b, tol, m) => assert(Math.abs(a - b) <= (tol || 1e-6), `${m || ''} expected ${b}, got ${a}`);
const blank = () => Object.fromEntries(E.STATS.map(s => [s, { inn: 0, aq: 0, raw: null }]));
const st = (slug, o) => ({ slug, level: 60, rank: 6, stats: blank(), ...(o || {}) });
const SET = () => E.settingsFrom({ A: { critRate: 0, otherAmp: 0, otherFinal: 0 } });
const one = (might, o) => ({ name: 'Test', kind: 'Physical', might, ep: 0, hits: 1, ...(o || {}) });
const run = (members, actions, target, o) => C.simulate(E, SET(), { members, actions, target: { hp: 1e9, def: 100, ...(target || {}) }, model: 'A', mightTotal: true, startEP: 100, maxEP: 100, ...(o || {}) });
const emb = (o, moves) => { const s = st('emberpup', o); s.stats.ATK.raw = 1000; s.stats.BREAK.raw = 300; return { name: 'Emberpup', st: s, moves: moves || [one(100)] }; };

t('model A by hand: (1000 − 100) × 100/100 × 1.5^0 crit … × 0.625 Alpha', () => { const r = run([emb()], [{ slot: 0, move: 0 }]); near(r.log[0].damage, 900 * 1 * 0.625, 1e-6); });
t('model B differs from model A', () => { const a = run([emb()], [{ slot: 0, move: 0 }]).total, b = run([emb()], [{ slot: 0, move: 0 }], {}, { model: 'B' }).total; near(b, (1000 - 100) * 0.625); const a2 = run([emb({}, [one(50)])], [{ slot: 0, move: 0 }]).total, b2 = run([emb({}, [one(50)])], [{ slot: 0, move: 0 }], {}, { model: 'B' }).total; assert(Math.abs(a2 - b2) > 1, a2 + ' ' + b2); });
t('defense floor: never below 10% of attack', () => { const r = run([emb()], [{ slot: 0, move: 0 }], { def: 5000 }); near(r.log[0].damage, 100 * 0.625, 1e-6); });
t('not an Alpha: no ×0.625', () => near(run([emb()], [{ slot: 0, move: 0 }], { wild: false }).total, 900, 1e-6));
t('BREAK state multiplier applied and recorded', () => { const r = run([emb()], [{ slot: 0, move: 0, state: 'break' }], { breakMult: 1.5 }); near(r.log[0].damage, 900 * 0.625 * 1.5, 1e-6); assert.strictEqual(r.log[0].state, 'break'); assert(r.log[0].mods.some(m => /BREAK state/.test(m.name) && m.status === 'unverified')); });
t('multi-hit: total Might split across hits, one log line per hit', () => { const r = run([emb({}, [one(90, { hits: 3 })])], [{ slot: 0, move: 0 }]); assert.strictEqual(r.log.length, 3); r.log.forEach(x => near(x.damage, (1000 - 100) * 30 / 100 * 0.625)); });
t('multi-hit: per-hit Might when set', () => { const r = run([emb({}, [one(90, { hits: 3, mightTotal: false })])], [{ slot: 0, move: 0 }]); near(r.log[0].damage, 900 * 0.9 * 0.625); });
t('EP: a move it cannot afford is refused', () => { const r = run([emb({}, [one(50, { ep: 60 })])], [{ slot: 0, move: 0 }, { slot: 0, move: 0 }]); assert(!r.log[0].error); assert(/Not enough team EP/.test(r.log[1].error)); });
t('cooldown blocks a repeat until ready', () => { const r = run([emb({}, [one(50, { cooldown: 5 })])], [{ slot: 0, move: 0 }, { slot: 0, move: 0, wait: 2 }, { slot: 0, move: 0, wait: 3 }]); assert(/Cooldown/.test(r.log[1].error)); assert(!r.log[2].error); });
t('team buff: Damage Amp and DEF shred last their duration', () => { const buffer = { name: 'B', st: st('emberpup'), moves: [one(0, { kind: 'buff', buff: { amp: 20, shred: 50, duration: 10 } })] };
  const r = run([buffer, emb()], [{ slot: 0, move: 0 }, { slot: 1, move: 0 }, { slot: 1, move: 0, wait: 11 }]); near(r.log[1].damage, (1000 - 50) * 1.2 * 0.625); near(r.log[2].damage, (1000 - 100) * 0.625); });
t('Ferocious Fang comes from the planner engine (+42 ATK at level 60)', () => { const r = run([emb({ item: 'h02', itemLv: 9 })], [{ slot: 0, move: 0 }]); near(r.log[0].damage, (1042 - 100) * 0.625, 1e-6); });
t('Vanguard\'s Whistle switches off once the target drops below 60%', () => { const r = run([emb({ item: 'h06', itemLv: 10 }, [one(100)])], [{ slot: 0, move: 0 }, { slot: 0, move: 0 }], { hp: 1000, def: 0 }); assert(r.log[0].mods.find(m => m.name === 'Final Damage Amp').value > 1); });
t('crit is capped at ×3', () => { const S = E.settingsFrom({ A: { critRate: 100, critDmg: 300 } }); const r = C.simulate(E, S, { members: [emb()], actions: [{ slot: 0, move: 0 }], target: { hp: 1e9, def: 0 }, model: 'A' }); near(r.log[0].mods.find(m => /Crit/.test(m.name)).value, 3, 1e-9); });
t('blank raw stats flag the hit as placeholder confidence', () => { const r = run([{ name: 'X', st: st('emberpup'), moves: [one(50)] }], [{ slot: 0, move: 0 }]); assert.strictEqual(r.log[0].confidence, 'placeholder'); assert(r.warnings.some(w => /placeholder/.test(w))); });
t('every hit names its source, time, modifiers and confidence', () => { const r = run([emb()], [{ slot: 0, move: 0, wait: 1.5 }]); const x = r.log[0]; assert(x.who && x.move && x.time === 1.5 && x.mods.length >= 10 && x.confidence); });
t('move presets: 13 checked moves, Might verified, unknown values left unknown', () => { const all = Object.values(GAME.moves).flat(); assert.strictEqual(all.length, 13); all.forEach(m => { assert.strictEqual(m.status.might, 'verified'); assert.strictEqual(m.cooldown, null); if (m.ep == null) assert.strictEqual(m.status.ep, 'unknown'); });
  assert(GAME.moves.fragrancier.some(m => m.name === 'Secret Fragrance Mark') && GAME.moves.fragrancier.some(m => m.name === 'Blossoming Moment')); });
/* reports */
const rep = () => { const cfg = { members: [emb()], actions: [{ slot: 0, move: 0, state: 'break' }], target: { name: 'Alpha Test', hp: 1e9, def: 100, breakMult: 1 }, model: 'A', mightTotal: true }; return R.make(cfg, C.simulate(E, SET(), cfg), { dataVersion: GAME.version }); };
t('report records model, state, equipment and confidence per hit', () => { const r = rep(); assert.strictEqual(r.model.id, 'A'); assert.strictEqual(r.steps[0].state, 'break'); assert.strictEqual(r.equipment[0].slug, 'emberpup'); assert(r.steps[0].confidence); });
t('observed damage within 5% is a match, beyond is a discrepancy', () => { const r = rep(); r.steps[0].observed = r.steps[0].predicted * 1.03; R.summarize(r); assert.strictEqual(r.steps[0].status, 'match'); r.steps[0].observed = r.steps[0].predicted * 1.2; R.summarize(r); assert.strictEqual(r.steps[0].status, 'discrepancy'); });
t('import recalculates totals and rejects bad data', () => { const r = rep(); r.steps[0].observed = r.steps[0].predicted; r.summary.matched = 999; assert.strictEqual(R.validate(JSON.parse(JSON.stringify(r))).summary.matched, 1);
  const bad = JSON.parse(JSON.stringify(r)); bad.steps[0].observed = -5; assert.throws(() => R.validate(bad)); const bad2 = JSON.parse(JSON.stringify(r)); bad2.steps[0].state = 'stunned'; assert.throws(() => R.validate(bad2)); });
t('evidence groups by model and BREAK state and needs repeats', () => { const rs = [rep(), rep(), rep()]; rs.forEach(r => { r.steps[0].observed = r.steps[0].predicted * 1.1; R.summarize(r); }); const g = R.groupEvidence(rs); assert.strictEqual(g.length, 1); assert.strictEqual(g[0].state, 'break'); assert.strictEqual(g[0].evidence, 'repeated'); near(g[0].medianErrorPct, 10, 0.01); });
t('CSV has one row per hit plus a header', () => { const r = rep(); assert.strictEqual(R.csv(r).split('\n').length, 2); assert(/model,mightTotal/.test(R.csv(r))); });
/* v10.10 */
t('BREAK multiplier of 0 stays 0; blank means no change', () => { near(run([emb()], [{ slot: 0, move: 0, state: 'break' }], { breakMult: 0 }).total, 0); near(run([emb()], [{ slot: 0, move: 0, state: 'break' }], { breakMult: '' }).total, 900 * 0.625); near(run([emb()], [{ slot: 0, move: 0, state: 'recovery' }], { recoveryMult: 0 }).total, 0); });
t('a move with unknown EP or cooldown marks the run incomplete, and says which', () => { const r = run([emb({}, [one(50, { ep: null, cooldown: null })])], [{ slot: 0, move: 0 }]); assert.strictEqual(r.complete, false); assert.deepStrictEqual(r.incomplete[0].missing, ['EP cost', 'cooldown']);
  const ok = run([emb({}, [one(50, { ep: 10, cooldown: 0 })])], [{ slot: 0, move: 0 }]); assert.strictEqual(ok.complete, true); });
const repOf = (atk, def, o) => { const m = emb(); m.st.stats.ATK.raw = atk; const cfg = { members: [m], actions: [{ slot: 0, move: 0 }], target: { name: 'Alpha Test', hp: 1e9, def, ...(o || {}) }, model: 'A', mightTotal: true };
  const r = R.make(cfg, C.simulate(E, SET(), cfg), { dataVersion: GAME.version, assumptions: { critRate: 0 } }); r.steps[0].observed = r.steps[0].predicted * 1.1; return R.summarize(r); };
t('evidence never mixes different setups (ATK 1000 vs 1500)', () => { const g = R.groupEvidence([repOf(1000, 100), repOf(1500, 100), repOf(1000, 100)]); assert.strictEqual(g.length, 2); assert.deepStrictEqual(g.map(x => x.samples).sort(), [1, 2]); });
t('evidence never mixes different target DEF', () => { assert.strictEqual(R.groupEvidence([repOf(1000, 100), repOf(1000, 300)]).length, 2); });
t('identical setups share one fingerprint', () => { assert.strictEqual(repOf(1000, 100).fingerprint, repOf(1000, 100).fingerprint); assert.notStrictEqual(repOf(1000, 100).fingerprint, repOf(1000, 100, { breakMult: 2 }).fingerprint); });
t('import rejects impossible setups', () => { const base = repOf(1000, 100), bad = (f, msg) => { const x = JSON.parse(JSON.stringify(base)); f(x); assert.throws(() => R.validate(x), msg); };
  bad(x => x.configuration.target.def = -50, /Target DEF/); bad(x => x.configuration.members[0].st.stats.ATK.raw = 9e9, /raw ATK/); bad(x => x.configuration.members[0].st.level = 90, /level/);
  bad(x => x.configuration.members[0].moves[0].hits = 0, /hits/); bad(x => x.configuration.actions[0].slot = 5, /slot/); bad(x => x.configuration.target.breakMult = -1, /BREAK/); bad(x => x.configuration.model = 'Z', /model/);
  assert.doesNotThrow(() => R.validate(JSON.parse(JSON.stringify(base)))); });
t('an imported fingerprint is recomputed, not trusted', () => { const x = JSON.parse(JSON.stringify(repOf(1000, 100))); const real = x.fingerprint; x.fingerprint = 'fake'; assert.strictEqual(R.validate(x).fingerprint, real); });
t('reports and CSV carry the setup fingerprint and complete flag', () => { const r = repOf(1000, 100); assert(r.fingerprint && r.complete === false && r.incomplete[0].missing.includes('cooldown')); assert(/setup,complete/.test(R.csv(r))); });
/* v10.11 */
t('EP is one shared team pool: a second Aniimo cannot spend what the first used', () => { const a = emb({}, [one(50, { ep: 60, cooldown: 0 })]), b2 = emb({}, [one(50, { ep: 60, cooldown: 0 })]);
  const r = run([a, b2], [{ slot: 0, move: 0 }, { slot: 1, move: 0 }]); assert(!r.log[0].error); assert(/Not enough team EP \(40 of 60\)/.test(r.log[1].error), r.log[1].error); });
t('EP before, cost, gain and after are recorded on every hit', () => { const r = run([emb({}, [one(30, { ep: 20, epGain: 5, cooldown: 0, hits: 2 })])], [{ slot: 0, move: 0 }]);
  r.log.forEach(x => { assert.strictEqual(x.epBefore, 100); assert.strictEqual(x.epCost, 20); assert.strictEqual(x.epGain, 5); assert.strictEqual(x.epAfter, 85); }); });
t('EP gain refills the shared pool for the next Aniimo', () => { const r = run([emb({}, [one(10, { ep: 60, epGain: 30, cooldown: 0 })]), emb({}, [one(10, { ep: 60, cooldown: 0 })])], [{ slot: 0, move: 0 }, { slot: 1, move: 0 }]); assert(!r.log[1].error, r.log[1].error); });
t('teams of 4 are accepted; 5 are refused', () => { const cfg = n => ({ members: Array.from({ length: n }, () => emb()), actions: [{ slot: 0, move: 0 }], target: { hp: 1e6, def: 0 }, model: 'A' });
  assert.doesNotThrow(() => R.checkConfig(cfg(4))); assert.throws(() => R.checkConfig(cfg(5)), /1 to 4/); assert.doesNotThrow(() => R.checkConfig(cfg(3))); });
t('same element is worked out when the move and form elements are known', () => { const r = run([emb({}, [one(100, { element: 'fire', cooldown: 0 }), one(100, { element: 'water', cooldown: 0 })])], [{ slot: 0, move: 0 }, { slot: 0, move: 1 }]);
  near(r.log[0].damage, 900 * 1.1 * 0.625); near(r.log[1].damage, 900 * 0.625); assert(r.log[0].mods.some(m => /move fire, form fire/.test(m.name) && m.status === 'verified')); });
t('with no move element the hand-ticked box is used and labelled', () => { const r = run([emb({}, [one(100, { sameElement: true, cooldown: 0 })])], [{ slot: 0, move: 0 }]); near(r.log[0].damage, 900 * 1.1 * 0.625); assert(r.log[0].mods.some(m => /ticked by hand/.test(m.name))); });
t('your measured DEF is labelled as yours', () => { const r = run([emb()], [{ slot: 0, move: 0 }], { defStatus: 'measured' }); assert(r.log[0].mods.some(m => /your measurement/.test(m.name) && m.status === 'measured')); });
t('Alpha list: 17 Alphas, each with element, region and a source; no invented HP or DEF', () => { assert.strictEqual(GAME.alphas.length, 17); GAME.alphas.forEach(a => { assert(a.elements.length && a.region && a.sources.length && E.bySlug[a.slug], a.name); assert.strictEqual(a.hp, null); assert.strictEqual(a.def, null); }); });
const brute = (members, S, opts) => { const pools = members.map((m, i) => [null, ...opts.poolFor(i)]); let best = -Infinity; const base = members.map(m => E.rankItems(m.st, S, m.goal, []).base.log);
  const go = (i, pick) => { if (i === members.length) { const ids = pick.filter(Boolean).map(p => p.id); if (!opts.allowDuplicates && new Set(ids).size !== ids.length) return;
    const tc = pick.reduce((t, p) => { if (!p) return t; const c0 = E.context(members[0].st, S); return t + E.itemEffects(p.id, p.lvl, c0, S.scenarios[S.scenario]).team.filter(x => x.kind === 'critRate').reduce((u, x) => u + x.v, 0); }, 0);
    let sc = 0; pick.forEach((p, k) => { const rr = E.rankItems(members[k].st, S, members[k].goal, p ? [p] : [], { teamCrit: tc }); const row = p ? rr.rows.find(x => x.id === p.id) || rr.base : rr.base; sc += members[k].weight * (row.log - base[k]); }); best = Math.max(best, sc); return; }
    pools[i].forEach(p => go(i + 1, [...pick, p])); }; go(0, []); return best; };
t('team item search is exhaustive and matches a full brute force (4 Aniimo, Bell team crit)', () => { const S = E.settingsFrom(); S.A.luckUptime.v = 100;
  const m = s => ({ st: st(s), goal: 'hit', weight: 1 }), members = ['emberpup', 'emberpup', 'flameruff', 'emberpup'].map(m), pool = ['h02', 'h06', 'h07', 'h16', 'h09'].map(id => ({ id, lvl: 15 }));
  const r = E.optimizeTeam(members, S, { inventory: null, allowDuplicates: false, poolFor: () => pool }); assert.strictEqual(r.search, 'exhaustive'); near(r.best.score, brute(members, S, { poolFor: () => pool, allowDuplicates: false }), 1e-9); });
console.log(`\n${pass} passed, ${fail} failed`); process.exit(fail ? 1 : 0);
